view: user_facts {
  derived_table: {
    explore_source: order_items {
      column: user_id {
        field: order_items.user_id
      }
      column: lifetime_orders {
        field: order_items.count
      }
      column: lifetime_value {
        field: order_items.total_sale_price
      }
    }
    datagroup_trigger: cicd_default_datagroup
  }

  dimension: user_id {
    primary_key: yes
    type: number
    description: "Unique user identifier matching users.id."
    sql: ${TABLE}.user_id ;;
  }

  dimension: lifetime_orders {
    type: number
    description: "Total count of orders placed by this user across their lifetime."
    sql: ${TABLE}.lifetime_orders ;;
  }

  dimension: lifetime_value {
    type: number
    description: "Total lifetime spend revenue generated by this user."
    value_format_name: usd
    sql: ${TABLE}.lifetime_value ;;
  }

  measure: average_lifetime_orders {
    type: average
    description: "Average lifetime order count across users."
    sql: ${lifetime_orders} ;;
  }

  measure: average_lifetime_value {
    type: average
    description: "Average lifetime value across users."
    value_format_name: usd
    sql: ${lifetime_value} ;;
  }
}
